### Obteniendo todos los Productos
GET http://localhost:1215/api/v1/product

### Obteniendo un Producto
GET http://localhost:1215/api/v1/product/60f608a65c90ac2480fe29d1

### creando un producto nuevo
POST http://localhost:1215/api/v1/product
token: token
Content-Type: application/json

{
    "name": "Producto 1",
	"description": "Producto 1 - Descripcion",
	"imgUrl": "https://github.com/code-and-cold/e-commerce-UIS",
	"price": 5000,
	"active": true
}

### Editando Producto
PUT http://localhost:1215/api/v1/product/60f608a65c90ac2480fe29d1
token: token
Content-Type: application/json

{
	"name": "Producto 12 xD",
	"description": "Producto 1 - Descripcion",
	"imgUrl": "https://github.com/code-and-cold/e-commerce-UIS",
	"price": 5000,
	"active": true
}

### Eliminando Producto
DELETE http://localhost:1215/api/v1/product/60f608b95c90ac2480fe29df
token: token
Content-Type: application/json

{
	"token": "token"
}
