### Ingresando a la Plataforma
POST http://localhost:1215/api/v1/user/login
Content-Type: application/json

{
    "email": "luis@gmail.com",
	"password": "Hola Mundo"
}

### Registrandose en la Plataforma
POST http://localhost:1215/api/v1/user
Content-Type: application/json

{
    "name": "LuisFOsG",
	"password": "Hola Mundo",
	"email": "luis@gmail.com"
}

### Obteniendo Datos de los Usuarios
GET http://localhost:1215/api/v1/user
token: token

### Obteniendo Datos de un Usuario
GET http://localhost:1215/api/v1/user/60f4f71489a144284429e63b
token: token

### Editando Datos de un Usuario
PUT http://localhost:1215/api/v1/user/60f4f71489a144284429e63b
token: token
Content-Type: application/json

{
	"name": "Luis",
    "password": "Hola Mundo",
	"email": "test@gmail.com"
}

### Eliminando a Un Usuario
DELETE http://localhost:1215/api/v1/user/60f4f71489a144284429e63b
token: token
