### Ingresando a la Plataforma
POST http://localhost:1215/api/v1/user/login
Content-Type: application/json

{
    "email": "test@gmail.com",
	"password": "Hola Mundo"
}

### Registrandose en la Plataforma
POST http://localhost:1215/api/v1/user
Content-Type: application/json

{
    "name": "LuisFOsG",
	"password": "Hola Mundo",
	"email": "luis@gmail.com"
}

### Obteniendo Datos de los Usuarios
GET http://localhost:1215/api/v1/user
Content-Type: application/json

{
    "token": "token"
}

### Obteniendo Datos de un Usuario
GET http://localhost:1215/api/v1/user/60f3929c63cd141c507cf519
Content-Type: application/json

{
    "token": "token"
}

### Editando Datos de un Usuario
PUT http://localhost:1215/api/v1/user/60f397ea14145426b01c7955
Content-Type: application/json

{
	"token": "token",
	"name": "Luis",
    "password": "Hola Mundo",
	"email": "test@gmail.com"
}

### Eliminando a Un Usuario
DELETE http://localhost:1215/api/v1/user/60f39ad0c1b81a2320465468
Content-Type: application/json

{
    "token": "token"
}
