### Ingresando a la Plataforma
POST http://localhost:1215/api/v1/user/login
Content-Type: application/json

{
    "email": "test@gmail.com",
	"password": "Hola Mundo"
}

### Registrandose en la Plataforma
POST http://localhost:1215/api/v1/user
Content-Type: application/json

{
    "name": "Luis",
	"password": "Hola Mundo",
	"email": "test@gmail.com"
}

### Obteniendo Datos de los Usuarios
GET http://localhost:1215/api/v1/user
token: token

### Obteniendo Datos de un Usuario
GET http://localhost:1215/api/v1/user/60f5f9ad64437736c0b6ec70
token: token

### Editando Datos de un Usuario
PUT http://localhost:1215/api/v1/user/60f5f9ad64437736c0b6ec70
token: token
Content-Type: application/json

{
	"name": "Luis",
    "password": "Hola Mundo",
	"email": "test@gmail.com"
}

### Eliminando a Un Usuario
DELETE http://localhost:1215/api/v1/user/60f5ffc9665ed21e906db024
token: token

### Dandole Admin a un Usuario
PUT http://localhost:1215/api/v1/user/admin/60f5ff8b665ed21e906db00b
token: token
